ALTER TABLE `Ticket` ADD COLUMN `email` VARCHAR(191) NULL;
ALTER TABLE `Ticket` ADD COLUMN `department` VARCHAR(191) NULL;
ALTER TABLE `RoomBooking` ADD COLUMN `email` VARCHAR(191) NULL;
ALTER TABLE `RoomBooking` ADD COLUMN `department` VARCHAR(191) NULL;
